name: New Relase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Changelog and Version
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0
          version-file: ./.version.yml
          skip-on-empty: true
      - name: Markdown to HTML
        id: md2html
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: lifepal/markdown-to-html@v1.2
        with:
          text: ${{ steps.changelog.outputs.clean_changelog }}
      - name: Archive Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: './dist/colorfulnotification@pcha.zip'
          exclusions: '*.git*,.version.yaml'
      - name: Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: Hs1r1us/Release-AIO@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          release_name: ${{ steps.changelog.outputs.tag }}
          asset_files: "./dist/colorfulnotification@pcha.zip"

